# control/navigation_command.py
"""Defines the NavigationCommand data structure, matching the C++ version."""

from dataclasses import dataclass
from enum import IntEnum

# --- Add this import for type hinting ---
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from navigation.mission_state import MissionState # To avoid circular import

class NavigationAction(IntEnum):
    """Actions the vehicle can take, matching C++ NavigationCommand::Action."""
    GO_STRAIGHT = 0
    TURN_LEFT = 1   # Follow left lane
    TURN_RIGHT = 2  # Follow right lane
    STOP_IN_START = 3 # Stop in the starting section (after 3 laps in Open)
    EXECUTE_PARKING = 4 # Initiate the parking sequence (after 3 laps in Obstacle)
    EMERGENCY_STOP = 5
    FOLLOW_LEFT_LANE = 6  # Explicit left lane following
    FOLLOW_RIGHT_LANE = 7 # Explicit right lane following
    # Add more actions if defined in C++

@dataclass
class NavigationCommand:
    """
    Represents a high-level navigation command generated by the PathPlanner.
    """
    action: NavigationAction = NavigationAction.GO_STRAIGHT
    desired_speed: float = 0.0 # Normalized or mapped speed command (e.g., 0.0 to 1.0)

    def __str__(self):
        return f"NavCmd(Action: {self.action.name}, Speed: {self.desired_speed:.2f})"

# Example usage (if run as script)
if __name__ == "__main__":
    cmd1 = NavigationCommand()
    print(cmd1)

    cmd2 = NavigationCommand(NavigationAction.TURN_LEFT, 0.7)
    print(cmd2)